AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  ExtraDetails: true
  UseCache: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/redmine_cli/helpers/monkey_patching.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
